# Generated by Django 4.1.3 on 2023-07-20 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoCatecory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=16)),
                ("color", models.CharField(max_length=7)),
                (
                    "tag",
                    models.ManyToManyField(related_name="todoCategory", to="tags.tag"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=24)),
                ("color", models.CharField(max_length=7)),
                ("priority", models.IntegerField()),
                ("deadline", models.DateTimeField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="todo",
                        to="todos.todocatecory",
                    ),
                ),
                ("tag", models.ManyToManyField(related_name="todo", to="tags.tag")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
