# Generated by Django 4.1.3 on 2023-07-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todocatecory",
            options={"verbose_name_plural": "Todo Categories"},
        ),
        migrations.AddField(
            model_name="todo",
            name="period",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
