# Generated by Django 4.1.3 on 2023-07-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todocatecory_options_todo_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_hard_deadline",
            field=models.BooleanField(default=False),
        ),
    ]
