# Generated by Django 4.1.3 on 2023-07-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_todo_is_hard_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="color",
        ),
        migrations.AddField(
            model_name="todo",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
