# Generated by Django 4.1.3 on 2023-08-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_alter_tagclass_options"),
        ("todos", "0004_remove_todo_color_todo_done"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TodoCatecory",
            new_name="TodoCategory",
        ),
    ]
