# Generated by Django 4.1.3 on 2023-07-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stockpiles", "0002_alter_stockpile_type_delete_stockpiletype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockpile",
            old_name="type",
            new_name="tag",
        ),
    ]
