# Generated by Django 4.1.3 on 2023-07-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagclass",
            options={"verbose_name_plural": "Tag Classes"},
        ),
    ]
