# Generated by Django 4.1.3 on 2023-09-03 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_alter_tagclass_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
                (
                    "tags",
                    models.ManyToManyField(related_name="tag_preset", to="tags.tag"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
