# Generated by Django 4.1.3 on 2023-11-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_tagpreset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="tagclass",
            name="name",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="tagpreset",
            name="name",
            field=models.CharField(max_length=12),
        ),
    ]
