# Generated by Django 4.1.3 on 2023-06-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("type", models.CharField(max_length=30)),
                ("amount", models.IntegerField()),
                ("memo", models.TextField()),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
    ]
