# Generated by Django 4.1.3 on 2023-07-12 22:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transactiontype_transaction_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionTypeClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                ("color", models.CharField(max_length=7)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="transactiontype",
            name="type_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type",
                to="transactions.transactiontypeclass",
            ),
        ),
    ]
