# Generated by Django 4.1.3 on 2023-07-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transactiontypeclass_transactiontype_type_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="memo",
            field=models.CharField(max_length=200),
        ),
    ]
