# Generated by Django 4.1.3 on 2023-07-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockpiles", "0001_initial"),
        ("transactions", "0004_alter_transaction_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="stockpile_transaction",
            field=models.ManyToManyField(
                related_name="mother_trxn", to="stockpiles.stockpiletransaction"
            ),
        ),
    ]
