# Generated by Django 4.1.3 on 2023-07-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("transactions", "0005_transaction_stockpile_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.ManyToManyField(related_name="transaction", to="tags.tag"),
        ),
        migrations.DeleteModel(
            name="TransactionType",
        ),
        migrations.DeleteModel(
            name="TransactionTypeClass",
        ),
    ]
