# Generated by Django 4.1.3 on 2023-07-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_transaction_type_delete_transactiontype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="type",
            new_name="tag",
        ),
    ]
