# Generated by Django 4.1.3 on 2023-07-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_paymethod_transaction_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymethod",
            name="currency",
            field=models.CharField(
                choices=[("KRW", "KRW"), ("USD", "USD"), ("JPY", "JPY")],
                default="KRW",
                max_length=3,
            ),
        ),
    ]
