# Generated by Django 4.1.3 on 2023-09-03 01:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_tagpreset"),
        ("transactions", "0009_paymethod_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
                ("amount", models.IntegerField()),
                (
                    "tag_preset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget",
                        to="tags.tagpreset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
